export const IMAGE_FORMATS = {
  UNKNOWN: "UNKNOWN",
  "3FR": "3FR", 
  "3G2": "3G2",
  "3GP": "3GP",
  A: "A",
  AAI: "AAI",
  AI: "AI",
  APNG: "APNG",
  ART: "ART",
  ARW: "ARW",
  ASHLAR: "ASHLAR",
  AVCI: "AVCI", 
  AVI: "AVI",
  AVIF: "AVIF",
  AVS: "AVS",
  B: "B",
  BAYER: "BAYER",
  BAYERA: "BAYERA",
  BGR: "BGR",
  BGRA: "BGRA",
  BGRO: "BGRO",
  BMP: "BMP",
  BMP2: "BMP2",
  BMP3: "BMP3",
  BRF: "BRF",
  C: "C",
  CAL: "CAL",
  CALS: "CALS",
  CANVAS: "CANVAS",
  CAPTION: "CAPTION",
  CIN: "CIN",
  CIP: "CIP",
  CLIP: "CLIP",
  CMYK: "CMYK",
  CMYKA: "CMYKA",
  CR2: "CR2",
  CR3: "CR3",
  CRW: "CRW",
  CUBE: "CUBE",
  CUR: "CUR",
  CUT: "CUT",
  DATA: "DATA",
  DCM: "DCM",
  DCR: "DCR",
  DCRAW: "DCRAW",
  DCX: "DCX",
  DDS: "DDS",
  DFONT: "DFONT",
  DNG: "DNG",
  DPX: "DPX",
  DXT1: "DXT1",
  DXT5: "DXT5",
  EPDF: "EPDF",
  EPI: "EPI",
  EPS: "EPS",
  EPS2: "EPS2",
  EPS3: "EPS3",
  EPSF: "EPSF",
  EPSI: "EPSI",
  EPT: "EPT",
  EPT2: "EPT2",
  EPT3: "EPT3",
  ERF: "ERF",
  EXR: "EXR",
  FARBFELD: "FARBFELD",
  FAX: "FAX",
  FF: "FF",
  FFF: "FFF",
  FILE: "FILE",
  FITS: "FITS",
  FL32: "FL32",
  FLV: "FLV",
  FRACTAL: "FRACTAL",
  FTP: "FTP",
  FTS: "FTS",
  FTXT: "FTXT",
  G: "G",
  G3: "G3",
  G4: "G4",
  GIF: "GIF",
  GIF87: "GIF87",
  GRADIENT: "GRADIENT",
  GRAY: "GRAY",
  GRAYA: "GRAYA",
  GROUP4: "GROUP4",
  HALD: "HALD",
  HDR: "HDR",
  HEIC: "HEIC",
  HEIF: "HEIF",
  HISTOGRAM: "HISTOGRAM",
  HRZ: "HRZ",
  HTM: "HTM",
  HTML: "HTML",
  HTTP: "HTTP",
  HTTPS: "HTTPS",
  ICB: "ICB",
  ICO: "ICO",
  ICON: "ICON",
  IIQ: "IIQ",
  INFO: "INFO",
  INLINE: "INLINE",
  IPL: "IPL",
  ISOBRL: "ISOBRL",
  ISOBRL6: "ISOBRL6",
  J2C: "J2C",
  J2K: "J2K",
  JNG: "JNG",
  JNX: "JNX",
  JP2: "JP2",
  JPC: "JPC",
  JPE: "JPE",
  JPEG: "JPEG",
  JPG: "JPG",
  JPM: "JPM",
  JPS: "JPS",
  JPT: "JPT",
  JSON: "JSON",
  JXL: "JXL",
  K: "K",
  K25: "K25",
  KDC: "KDC",
  LABEL: "LABEL",
  M: "M",
  M2V: "M2V",
  M4V: "M4V",
  MAC: "MAC",
  MAP: "MAP",
  MASK: "MASK",
  MAT: "MAT",
  MATTE: "MATTE",
  MDC: "MDC",
  MEF: "MEF",
  MIFF: "MIFF",
  MKV: "MKV",
  MNG: "MNG",
  MONO: "MONO",
  MOV: "MOV",
  MOS: "MOS",
  MP4: "MP4",
  MPC: "MPC",
  MPEG: "MPEG",
  MPG: "MPG",
  MPO: "MPO",
  MRW: "MRW",
  MSL: "MSL",
  MSVG: "MSVG",
  MTV: "MTV",
  MVG: "MVG",
  NEF: "NEF",
  NRW: "NRW",
  NULL: "NULL",
  O: "O",
  ORA: "ORA",
  ORF: "ORF",
  OTB: "OTB",
  OTF: "OTF",
  PAL: "PAL",
  PALM: "PALM",
  PAM: "PAM",
  PANGO: "PANGO",
  PATTERN: "PATTERN",
  PBM: "PBM",
  PCD: "PCD",
  PCDS: "PCDS",
  PCL: "PCL",
  PCT: "PCT",
  PCX: "PCX",
  PDB: "PDB",
  PDF: "PDF",
  PDFA: "PDFA",
  PEF: "PEF",
  PES: "PES",
  PFA: "PFA",
  PFB: "PFB",
  PFM: "PFM",
  PGM: "PGM",
  PGX: "PGX",
  PHM: "PHM",
  PICON: "PICON",
  PICT: "PICT",
  PIX: "PIX",
  PJPEG: "PJPEG",
  PLASMA: "PLASMA",
  PNG: "PNG",
  PNG00: "PNG00",
  PNG24: "PNG24",
  PNG32: "PNG32",
  PNG48: "PNG48",
  PNG64: "PNG64",
  PNG8: "PNG8",
  PNM: "PNM",
  POCKETMOD: "POCKETMOD",
  PPM: "PPM",
  PS: "PS",
  PS2: "PS2",
  PS3: "PS3",
  PSB: "PSB",
  PSD: "PSD",
  PTIF: "PTIF",
  PWP: "PWP",
  QOI: "QOI",
  R: "R",
  RAF: "RAF",
  RAS: "RAS",
  RAW: "RAW",
  RGB: "RGB",
  RGB565: "RGB565",
  RGBA: "RGBA",
  RGBO: "RGBO",
  RGF: "RGF",
  RLA: "RLA",
  RLE: "RLE",
  RMF: "RMF",
  RW2: "RW2",
  RWL: "RWL",
  SCR: "SCR",
  SCREENSHOT: "SCREENSHOT",
  SCT: "SCT",
  SFW: "SFW",
  SGI: "SGI",
  SHTML: "SHTML",
  SIX: "SIX",
  SIXEL: "SIXEL",
  SR2: "SR2",
  SRF: "SRF",
  SRW: "SRW",
  STEGANO: "STEGANO",
  STI: "STI",
  STRIMG: "STRIMG",
  SUN: "SUN",
  SVG: "SVG",
  SVGZ: "SVGZ",
  TEXT: "TEXT",
  TGA: "TGA",
  THUMBNAIL: "THUMBNAIL",
  TIF: "TIF",
  TIFF: "TIFF",
  TIFF64: "TIFF64",
  TILE: "TILE",
  TIM: "TIM",
  TM2: "TM2",
  TTC: "TTC",
  TTF: "TTF",
  TXT: "TXT",
  UBRL: "UBRL",
  UBRL6: "UBRL6",
  UIL: "UIL",
  UYVY: "UYVY",
  VDA: "VDA",
  VICAR: "VICAR",
  VID: "VID",
  VIFF: "VIFF",
  VIPS: "VIPS",
  VST: "VST",
  WEBM: "WEBM",
  WEBP: "WEBP",
  WBMP: "WBMP",
  WMV: "WMV",
  WPG: "WPG",
  X3F: "X3F",
  XBM: "XBM",
  XC: "XC",
  XCF: "XCF",
  XPM: "XPM",
  XPS: "XPS",
  XV: "XV",
  Y: "Y",
  YAML: "YAML",
  YCBCR: "YCBCR",
  YCBCRA: "YCBCRA",
  YUV: "YUV"
} as const;

export const COMMON_FORMATS = [
  { value: IMAGE_FORMATS.UNKNOWN, label: "UNKNOWN" },
  { value: IMAGE_FORMATS["3FR"], label: "3FR" },
  { value: IMAGE_FORMATS["3G2"], label: "3G2" },
  { value: IMAGE_FORMATS["3GP"], label: "3GP" },
  { value: IMAGE_FORMATS.A, label: "A" },
  { value: IMAGE_FORMATS.AAI, label: "AAI" },
  { value: IMAGE_FORMATS.AI, label: "AI" },
  { value: IMAGE_FORMATS.APNG, label: "APNG" },
  { value: IMAGE_FORMATS.ART, label: "ART" },
  { value: IMAGE_FORMATS.ARW, label: "ARW" },
  { value: IMAGE_FORMATS.ASHLAR, label: "ASHLAR" },
  { value: IMAGE_FORMATS.AVCI, label: "AVCI" },
  { value: IMAGE_FORMATS.AVI, label: "AVI" },
  { value: IMAGE_FORMATS.AVIF, label: "AVIF" },
  { value: IMAGE_FORMATS.AVS, label: "AVS" },
  { value: IMAGE_FORMATS.B, label: "B" },
  { value: IMAGE_FORMATS.BAYER, label: "BAYER" },
  { value: IMAGE_FORMATS.BAYERA, label: "BAYERA" },
  { value: IMAGE_FORMATS.BGR, label: "BGR" },
  { value: IMAGE_FORMATS.BGRA, label: "BGRA" },
  { value: IMAGE_FORMATS.BGRO, label: "BGRO" },
  { value: IMAGE_FORMATS.BMP, label: "BMP" },
  { value: IMAGE_FORMATS.BMP2, label: "BMP2" },
  { value: IMAGE_FORMATS.BMP3, label: "BMP3" },
  { value: IMAGE_FORMATS.BRF, label: "BRF" },
  { value: IMAGE_FORMATS.C, label: "C" },
  { value: IMAGE_FORMATS.CAL, label: "CAL" },
  { value: IMAGE_FORMATS.CALS, label: "CALS" },
  { value: IMAGE_FORMATS.CANVAS, label: "CANVAS" },
  { value: IMAGE_FORMATS.CAPTION, label: "CAPTION" },
  { value: IMAGE_FORMATS.CIN, label: "CIN" },
  { value: IMAGE_FORMATS.CIP, label: "CIP" },
  { value: IMAGE_FORMATS.CLIP, label: "CLIP" },
  { value: IMAGE_FORMATS.CMYK, label: "CMYK" },
  { value: IMAGE_FORMATS.CMYKA, label: "CMYKA" },
  { value: IMAGE_FORMATS.CR2, label: "CR2" },
  { value: IMAGE_FORMATS.CR3, label: "CR3" },
  { value: IMAGE_FORMATS.CRW, label: "CRW" },
  { value: IMAGE_FORMATS.CUBE, label: "CUBE" },
  { value: IMAGE_FORMATS.CUR, label: "CUR" },
  { value: IMAGE_FORMATS.CUT, label: "CUT" },
  { value: IMAGE_FORMATS.DATA, label: "DATA" },
  { value: IMAGE_FORMATS.DCM, label: "DCM" },
  { value: IMAGE_FORMATS.DCR, label: "DCR" },
  { value: IMAGE_FORMATS.DCRAW, label: "DCRAW" },
  { value: IMAGE_FORMATS.DCX, label: "DCX" },
  { value: IMAGE_FORMATS.DDS, label: "DDS" },
  { value: IMAGE_FORMATS.DFONT, label: "DFONT" },
  { value: IMAGE_FORMATS.DNG, label: "DNG" },
  { value: IMAGE_FORMATS.DPX, label: "DPX" },
  { value: IMAGE_FORMATS.DXT1, label: "DXT1" },
  { value: IMAGE_FORMATS.DXT5, label: "DXT5" },
  { value: IMAGE_FORMATS.EPDF, label: "EPDF" },
  { value: IMAGE_FORMATS.EPI, label: "EPI" },
  { value: IMAGE_FORMATS.EPS, label: "EPS" },
  { value: IMAGE_FORMATS.EPS2, label: "EPS2" },
  { value: IMAGE_FORMATS.EPS3, label: "EPS3" },
  { value: IMAGE_FORMATS.EPSF, label: "EPSF" },
  { value: IMAGE_FORMATS.EPSI, label: "EPSI" },
  { value: IMAGE_FORMATS.EPT, label: "EPT" },
  { value: IMAGE_FORMATS.EPT2, label: "EPT2" },
  { value: IMAGE_FORMATS.EPT3, label: "EPT3" },
  { value: IMAGE_FORMATS.ERF, label: "ERF" },
  { value: IMAGE_FORMATS.EXR, label: "EXR" },
  { value: IMAGE_FORMATS.FARBFELD, label: "FARBFELD" },
  { value: IMAGE_FORMATS.FAX, label: "FAX" },
  { value: IMAGE_FORMATS.FF, label: "FF" },
  { value: IMAGE_FORMATS.FFF, label: "FFF" },
  { value: IMAGE_FORMATS.FILE, label: "FILE" },
  { value: IMAGE_FORMATS.FITS, label: "FITS" },
  { value: IMAGE_FORMATS.FL32, label: "FL32" },
  { value: IMAGE_FORMATS.FLV, label: "FLV" },
  { value: IMAGE_FORMATS.FRACTAL, label: "FRACTAL" },
  { value: IMAGE_FORMATS.FTP, label: "FTP" },
  { value: IMAGE_FORMATS.FTS, label: "FTS" },
  { value: IMAGE_FORMATS.FTXT, label: "FTXT" },
  { value: IMAGE_FORMATS.G, label: "G" },
  { value: IMAGE_FORMATS.G3, label: "G3" },
  { value: IMAGE_FORMATS.G4, label: "G4" },
  { value: IMAGE_FORMATS.GIF, label: "GIF" },
  { value: IMAGE_FORMATS.GIF87, label: "GIF87" },
  { value: IMAGE_FORMATS.GRADIENT, label: "GRADIENT" },
  { value: IMAGE_FORMATS.GRAY, label: "GRAY" },
  { value: IMAGE_FORMATS.GRAYA, label: "GRAYA" },
  { value: IMAGE_FORMATS.GROUP4, label: "GROUP4" },
  { value: IMAGE_FORMATS.HALD, label: "HALD" },
  { value: IMAGE_FORMATS.HDR, label: "HDR" },
  { value: IMAGE_FORMATS.HEIC, label: "HEIC" },
  { value: IMAGE_FORMATS.HEIF, label: "HEIF" },
  { value: IMAGE_FORMATS.HISTOGRAM, label: "HISTOGRAM" },
  { value: IMAGE_FORMATS.HRZ, label: "HRZ" },
  { value: IMAGE_FORMATS.HTM, label: "HTM" },
  { value: IMAGE_FORMATS.HTML, label: "HTML" },
  { value: IMAGE_FORMATS.HTTP, label: "HTTP" },
  { value: IMAGE_FORMATS.HTTPS, label: "HTTPS" },
  { value: IMAGE_FORMATS.ICB, label: "ICB" },
  { value: IMAGE_FORMATS.ICO, label: "ICO" },
  { value: IMAGE_FORMATS.ICON, label: "ICON" },
  { value: IMAGE_FORMATS.IIQ, label: "IIQ" },
  { value: IMAGE_FORMATS.INFO, label: "INFO" },
  { value: IMAGE_FORMATS.INLINE, label: "INLINE" },
  { value: IMAGE_FORMATS.IPL, label: "IPL" },
  { value: IMAGE_FORMATS.ISOBRL, label: "ISOBRL" },
  { value: IMAGE_FORMATS.ISOBRL6, label: "ISOBRL6" },
  { value: IMAGE_FORMATS.J2C, label: "J2C" },
  { value: IMAGE_FORMATS.J2K, label: "J2K" },
  { value: IMAGE_FORMATS.JNG, label: "JNG" },
  { value: IMAGE_FORMATS.JNX, label: "JNX" },
  { value: IMAGE_FORMATS.JP2, label: "JP2" },
  { value: IMAGE_FORMATS.JPC, label: "JPC" },
  { value: IMAGE_FORMATS.JPE, label: "JPE" },
  { value: IMAGE_FORMATS.JPEG, label: "JPEG" },
  { value: IMAGE_FORMATS.JPG, label: "JPG" },
  { value: IMAGE_FORMATS.JPM, label: "JPM" },
  { value: IMAGE_FORMATS.JPS, label: "JPS" },
  { value: IMAGE_FORMATS.JPT, label: "JPT" },
  { value: IMAGE_FORMATS.JSON, label: "JSON" },
  { value: IMAGE_FORMATS.JXL, label: "JXL" },
  { value: IMAGE_FORMATS.K, label: "K" },
  { value: IMAGE_FORMATS.K25, label: "K25" },
  { value: IMAGE_FORMATS.KDC, label: "KDC" },
  { value: IMAGE_FORMATS.LABEL, label: "LABEL" },
  { value: IMAGE_FORMATS.M, label: "M" },
  { value: IMAGE_FORMATS.M2V, label: "M2V" },
  { value: IMAGE_FORMATS.M4V, label: "M4V" },
  { value: IMAGE_FORMATS.MAC, label: "MAC" },
  { value: IMAGE_FORMATS.MAP, label: "MAP" },
  { value: IMAGE_FORMATS.MASK, label: "MASK" },
  { value: IMAGE_FORMATS.MAT, label: "MAT" },
  { value: IMAGE_FORMATS.MATTE, label: "MATTE" },
  { value: IMAGE_FORMATS.MDC, label: "MDC" },
  { value: IMAGE_FORMATS.MEF, label: "MEF" },
  { value: IMAGE_FORMATS.MIFF, label: "MIFF" },
  { value: IMAGE_FORMATS.MKV, label: "MKV" },
  { value: IMAGE_FORMATS.MNG, label: "MNG" },
  { value: IMAGE_FORMATS.MONO, label: "MONO" },
  { value: IMAGE_FORMATS.MOV, label: "MOV" },
  { value: IMAGE_FORMATS.MOS, label: "MOS" },
  { value: IMAGE_FORMATS.MP4, label: "MP4" },
  { value: IMAGE_FORMATS.MPC, label: "MPC" },
  { value: IMAGE_FORMATS.MPEG, label: "MPEG" },
  { value: IMAGE_FORMATS.MPG, label: "MPG" },
  { value: IMAGE_FORMATS.MPO, label: "MPO" },
  { value: IMAGE_FORMATS.MRW, label: "MRW" },
  { value: IMAGE_FORMATS.MSL, label: "MSL" },
  { value: IMAGE_FORMATS.MSVG, label: "MSVG" },
  { value: IMAGE_FORMATS.MTV, label: "MTV" },
  { value: IMAGE_FORMATS.MVG, label: "MVG" },
  { value: IMAGE_FORMATS.NEF, label: "NEF" },
  { value: IMAGE_FORMATS.NRW, label: "NRW" },
  { value: IMAGE_FORMATS.NULL, label: "NULL" },
  { value: IMAGE_FORMATS.O, label: "O" },
  { value: IMAGE_FORMATS.ORA, label: "ORA" },
  { value: IMAGE_FORMATS.ORF, label: "ORF" },
  { value: IMAGE_FORMATS.OTB, label: "OTB" },
  { value: IMAGE_FORMATS.OTF, label: "OTF" },
  { value: IMAGE_FORMATS.PAL, label: "PAL" },
  { value: IMAGE_FORMATS.PALM, label: "PALM" },
  { value: IMAGE_FORMATS.PAM, label: "PAM" },
  { value: IMAGE_FORMATS.PANGO, label: "PANGO" },
  { value: IMAGE_FORMATS.PATTERN, label: "PATTERN" },
  { value: IMAGE_FORMATS.PBM, label: "PBM" },
  { value: IMAGE_FORMATS.PCD, label: "PCD" },
  { value: IMAGE_FORMATS.PCDS, label: "PCDS" },
  { value: IMAGE_FORMATS.PCL, label: "PCL" },
  { value: IMAGE_FORMATS.PCT, label: "PCT" },
  { value: IMAGE_FORMATS.PCX, label: "PCX" },
  { value: IMAGE_FORMATS.PDB, label: "PDB" },
  { value: IMAGE_FORMATS.PDF, label: "PDF" },
  { value: IMAGE_FORMATS.PDFA, label: "PDFA" },
  { value: IMAGE_FORMATS.PEF, label: "PEF" },
  { value: IMAGE_FORMATS.PES, label: "PES" },
  { value: IMAGE_FORMATS.PFA, label: "PFA" },
  { value: IMAGE_FORMATS.PFB, label: "PFB" },
  { value: IMAGE_FORMATS.PFM, label: "PFM" },
  { value: IMAGE_FORMATS.PGM, label: "PGM" },
  { value: IMAGE_FORMATS.PGX, label: "PGX" },
  { value: IMAGE_FORMATS.PHM, label: "PHM" },
  { value: IMAGE_FORMATS.PICON, label: "PICON" },
  { value: IMAGE_FORMATS.PICT, label: "PICT" },
  { value: IMAGE_FORMATS.PIX, label: "PIX" },
  { value: IMAGE_FORMATS.PJPEG, label: "PJPEG" },
  { value: IMAGE_FORMATS.PLASMA, label: "PLASMA" },
  { value: IMAGE_FORMATS.PNG, label: "PNG" },
  { value: IMAGE_FORMATS.PNG00, label: "PNG00" },
  { value: IMAGE_FORMATS.PNG24, label: "PNG24" },
  { value: IMAGE_FORMATS.PNG32, label: "PNG32" },
  { value: IMAGE_FORMATS.PNG48, label: "PNG48" },
  { value: IMAGE_FORMATS.PNG64, label: "PNG64" },
  { value: IMAGE_FORMATS.PNG8, label: "PNG8" },
  { value: IMAGE_FORMATS.PNM, label: "PNM" },
  { value: IMAGE_FORMATS.POCKETMOD, label: "POCKETMOD" },
  { value: IMAGE_FORMATS.PPM, label: "PPM" },
  { value: IMAGE_FORMATS.PS, label: "PS" },
  { value: IMAGE_FORMATS.PS2, label: "PS2" },
  { value: IMAGE_FORMATS.PS3, label: "PS3" },
  { value: IMAGE_FORMATS.PSB, label: "PSB" },
  { value: IMAGE_FORMATS.PSD, label: "PSD" },
  { value: IMAGE_FORMATS.PTIF, label: "PTIF" },
  { value: IMAGE_FORMATS.PWP, label: "PWP" },
  { value: IMAGE_FORMATS.QOI, label: "QOI" },
  { value: IMAGE_FORMATS.R, label: "R" },
  { value: IMAGE_FORMATS.RAF, label: "RAF" },
  { value: IMAGE_FORMATS.RAS, label: "RAS" },
  { value: IMAGE_FORMATS.RAW, label: "RAW" },
  { value: IMAGE_FORMATS.RGB, label: "RGB" },
  { value: IMAGE_FORMATS.RGB565, label: "RGB565" },
  { value: IMAGE_FORMATS.RGBA, label: "RGBA" },
  { value: IMAGE_FORMATS.RGBO, label: "RGBO" },
  { value: IMAGE_FORMATS.RGF, label: "RGF" },
  { value: IMAGE_FORMATS.RLA, label: "RLA" },
  { value: IMAGE_FORMATS.RLE, label: "RLE" },
  { value: IMAGE_FORMATS.RMF, label: "RMF" },
  { value: IMAGE_FORMATS.RW2, label: "RW2" },
  { value: IMAGE_FORMATS.RWL, label: "RWL" },
  { value: IMAGE_FORMATS.SCR, label: "SCR" },
  { value: IMAGE_FORMATS.SCREENSHOT, label: "SCREENSHOT" },
  { value: IMAGE_FORMATS.SCT, label: "SCT" },
  { value: IMAGE_FORMATS.SFW, label: "SFW" },
  { value: IMAGE_FORMATS.SGI, label: "SGI" },
  { value: IMAGE_FORMATS.SHTML, label: "SHTML" },
  { value: IMAGE_FORMATS.SIX, label: "SIX" },
  { value: IMAGE_FORMATS.SIXEL, label: "SIXEL" },
  { value: IMAGE_FORMATS.SR2, label: "SR2" },
  { value: IMAGE_FORMATS.SRF, label: "SRF" },
  { value: IMAGE_FORMATS.SRW, label: "SRW" },
  { value: IMAGE_FORMATS.STEGANO, label: "STEGANO" },
  { value: IMAGE_FORMATS.STI, label: "STI" },
  { value: IMAGE_FORMATS.STRIMG, label: "STRIMG" },
  { value: IMAGE_FORMATS.SUN, label: "SUN" },
  { value: IMAGE_FORMATS.SVG, label: "SVG" },
  { value: IMAGE_FORMATS.SVGZ, label: "SVGZ" },
  { value: IMAGE_FORMATS.TEXT, label: "TEXT" },
  { value: IMAGE_FORMATS.TGA, label: "TGA" },
  { value: IMAGE_FORMATS.THUMBNAIL, label: "THUMBNAIL" },
  { value: IMAGE_FORMATS.TIF, label: "TIF" },
  { value: IMAGE_FORMATS.TIFF, label: "TIFF" },
  { value: IMAGE_FORMATS.TIFF64, label: "TIFF64" },
  { value: IMAGE_FORMATS.TILE, label: "TILE" },
  { value: IMAGE_FORMATS.TIM, label: "TIM" },
  { value: IMAGE_FORMATS.TM2, label: "TM2" },
  { value: IMAGE_FORMATS.TTC, label: "TTC" },
  { value: IMAGE_FORMATS.TTF, label: "TTF" },
  { value: IMAGE_FORMATS.TXT, label: "TXT" },
  { value: IMAGE_FORMATS.UBRL, label: "UBRL" },
  { value: IMAGE_FORMATS.UBRL6, label: "UBRL6" },
  { value: IMAGE_FORMATS.UIL, label: "UIL" },
  { value: IMAGE_FORMATS.UYVY, label: "UYVY" },
  { value: IMAGE_FORMATS.VDA, label: "VDA" },
  { value: IMAGE_FORMATS.VICAR, label: "VICAR" },
  { value: IMAGE_FORMATS.VID, label: "VID" },
  { value: IMAGE_FORMATS.VIFF, label: "VIFF" },
  { value: IMAGE_FORMATS.VIPS, label: "VIPS" },
  { value: IMAGE_FORMATS.VST, label: "VST" },
  { value: IMAGE_FORMATS.WEBM, label: "WEBM" },
  { value: IMAGE_FORMATS.WEBP, label: "WEBP" },
  { value: IMAGE_FORMATS.WBMP, label: "WBMP" },
  { value: IMAGE_FORMATS.WMV, label: "WMV" },
  { value: IMAGE_FORMATS.WPG, label: "WPG" },
  { value: IMAGE_FORMATS.X3F, label: "X3F" },
  { value: IMAGE_FORMATS.XBM, label: "XBM" },
  { value: IMAGE_FORMATS.XC, label: "XC" },
  { value: IMAGE_FORMATS.XCF, label: "XCF" },
  { value: IMAGE_FORMATS.XPM, label: "XPM" },
  { value: IMAGE_FORMATS.XPS, label: "XPS" },
  { value: IMAGE_FORMATS.XV, label: "XV" },
  { value: IMAGE_FORMATS.Y, label: "Y" },
  { value: IMAGE_FORMATS.YAML, label: "YAML" },
  { value: IMAGE_FORMATS.YCBCR, label: "YCBCR" },
  { value: IMAGE_FORMATS.YCBCRA, label: "YCBCRA" },
  { value: IMAGE_FORMATS.YUV, label: "YUV" }
] as const;

export type ImageFormat = typeof IMAGE_FORMATS[keyof typeof IMAGE_FORMATS];